import Head from "next/head"
import React from "react"

function Title() {
  return (
    <Head>
      <title>AWESOME FOOD STORE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Title
